name: Generate User Config

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'User ID'
        required: true
      tenant:
        description: 'CIAM Tenant name (e.g., sunnylinkth)'
        required: true
      client_id:
        description: 'Azure AD Client ID'
        required: true
      cache_file:
        description: 'MSAL Cache File Name'
        default: 'msal_cache.txt'
      cache_dir:
        description: 'MSAL Cache Directory'
        default: 'C:/temp'
      scopes:
        description: 'API Scopes'
        default: 'openid offline_access'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate JSON File
        run: |
          mkdir -p data
          cat <<EOF > data/${{ github.event.inputs.user_id }}.json
          {
            "AzureAd": {
              "Authority": "https://${{ github.event.inputs.tenant }}.ciamlogin.com/",
              "ClientId": "${{ github.event.inputs.client_id }}",
              "CacheFileName": "${{ github.event.inputs.cache_file }}",
              "CacheDir": "${{ github.event.inputs.cache_dir }}"
            },
            "DownstreamApi": {
              "Scopes": "${{ github.event.inputs.scopes }}"
            }
          }
          EOF

      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add data/${{ github.event.inputs.user_id }}.json
          git commit -m "Add config for ${{ github.event.inputs.user_id }}"
          git push
