name: Generate User Config

on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'CIAM Tenant name (e.g., xyz123)'
        required: true
      client_id:
        description: 'Azure AD Application (client) ID'
        required: true
      tenant_id:
        description: 'Azure Directory (tenant) ID'
        required: true
      cache_file:
        description: 'MSAL Cache File Name'
        default: 'msal_cache.txt'
      cache_dir:
        description: 'MSAL Cache Directory'
        default: 'C:/temp'
      scopes:
        description: 'API Scopes'
        default: 'openid offline_access User.Read Sites.ReadWrite.All'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # important: disable default token

      - name: Generate JSON File
        run: |
          mkdir -p data
          cat <<EOF > data/${{ github.event.inputs.tenant }}.json
          {
            "AzureAd": {
              "Authority": "https://${{ github.event.inputs.tenant }}.ciamlogin.com/",
              "ClientId": "${{ github.event.inputs.client_id }}",
              "TenantId": "${{ github.event.inputs.tenant_id }}",
              "CacheFileName": "${{ github.event.inputs.cache_file }}",
              "CacheDir": "${{ github.event.inputs.cache_dir }}"
            },
            "DownstreamApi": {
              "Scopes": "${{ github.event.inputs.scopes }}"
            }
          }
          EOF

      - name: Commit and Push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add data/${{ github.event.inputs.user_id }}.json
          git commit -m "Add config for ${{ github.event.inputs.user_id }}" || echo "No changes to commit"
          git push https://${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main
